#! /usr/bin/env python3
# vim:fenc=utf-8
#
# Copyright © 2023 veypi <i@veypi.com>
#
# Distributed under terms of the MIT license.

"""

"""

import requests

response = requests.get(url='http://c0.veypi.com/status')
print([response.text])
